apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kubernetesjmdaks-d0ed"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kubernetesjmdaks-d0ed"
  template:
    metadata:
      labels:
        app: "kubernetesjmdaks-d0ed"
    spec:
      containers:
        - name: "kubernetesjmdaks-d0ed"
          image: "containerregistryjmd.azurecr.io/kubernetesjmdaks"
          ports:
          - containerPort: 80